apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
        - name: crm
          image: crm:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: crm-balancer
spec:
  selector:
    app: crm
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
